# Generated by Django 5.2.2 on 2025-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amenities', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomtype',
            name='amenities',
            field=models.ManyToManyField(blank=True, to='amenities.amenity', verbose_name='Tiện ích'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='capacity',
            field=models.IntegerField(help_text='Số lượng khách tối đa'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='description',
            field=models.TextField(blank=True, verbose_name='Mô tả'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Tên loại phòng'),
        ),
        migrations.AlterField(
            model_name='roomtype',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá một đêm'),
        ),
    ]
