# Generated by Django 5.2.2 on 2025-06-21 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Amenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Tên tiện ích')),
                ('description', models.TextField(blank=True, verbose_name='Mô tả')),
                ('icon_class', models.CharField(blank=True, max_length=255, verbose_name='Lớp icon')),
            ],
            options={
                'verbose_name_plural': 'Amenities',
            },
        ),
    ]
